/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfac;

import javax.swing.JOptionPane;
import report.GerarFichasFirebird;

/**
 * Usuario pode CONSULTAR, Cadastrar, Alterar e Excluir NOVO CLIENTE e/ou
 * TRANSPORTADORA
 *
 */
public class jFicha extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifCadastro
     */
    public jFicha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlConsulta = new javax.swing.JLabel();
        jcTipo = new javax.swing.JComboBox<>();
        jtInfo = new javax.swing.JTextField();
        jlInfo = new javax.swing.JLabel();
        jbFicha = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gerar Ficha");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jlConsulta.setText("Imprimir por:");

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cod.", "Cidade", "Estado" }));

        jlInfo.setText("Digite a informação:");

        jbFicha.setText("Gerar Ficha(s)");
        jbFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbFicha, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jtInfo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbFicha)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setBounds(115, 20, 202, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        jInit.Excel = true;


    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        jInit.Excel = false;
        dispose();
    }//GEN-LAST:event_formInternalFrameClosed

    private void jbFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFichaActionPerformed
        // TODO add your handling code here:

        String tipo = "";
        String escolha = jcTipo.getSelectedItem().toString().trim();

        if (escolha.equals("Cod.")) {
            tipo = " " + "clientes.K_COD";
        }
        if (escolha.equals("Cidade")) {
            tipo = " " + "clientes.K_MUNFIS";
        }
        if (escolha.equals("Estado")) {
            tipo = " " + "clientes.K_ESTFIS";
        }

        String arg = jtInfo.getText().toUpperCase();

        GerarFichasFirebird rel = new GerarFichasFirebird();

        try {

            rel.fichas("C:\\Users\\user\\Desktop\\NetBeansProjects\\ArmagedonExcel\\FichaFirebird\\fichas.jasper", tipo, arg);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar ficha " + e);

        }

    }//GEN-LAST:event_jbFichaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbFicha;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JLabel jlConsulta;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JTextField jtInfo;
    // End of variables declaration//GEN-END:variables
}